// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzflo4sWD4wIyU6hFKco14subtVlKOP-k',
    appId: '1:951446477589:web:0bea29676c8fb57857e71c',
    messagingSenderId: '951446477589',
    projectId: 'shop-games-user-registros',
    authDomain: 'shop-games-user-registros.firebaseapp.com',
    storageBucket: 'shop-games-user-registros.appspot.com',
    measurementId: 'G-R2QH6ZJKVK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOZV5WqqWD4s2iEfrFcZF_gjOw_XNYDK0',
    appId: '1:951446477589:android:79db524cd9f9a54c57e71c',
    messagingSenderId: '951446477589',
    projectId: 'shop-games-user-registros',
    storageBucket: 'shop-games-user-registros.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvKzJz2txqAZSggZMu6Jh8pg-ok9M-FLI',
    appId: '1:951446477589:ios:8463464bd47957f957e71c',
    messagingSenderId: '951446477589',
    projectId: 'shop-games-user-registros',
    storageBucket: 'shop-games-user-registros.appspot.com',
    iosBundleId: 'com.example.shopGamesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvKzJz2txqAZSggZMu6Jh8pg-ok9M-FLI',
    appId: '1:951446477589:ios:8463464bd47957f957e71c',
    messagingSenderId: '951446477589',
    projectId: 'shop-games-user-registros',
    storageBucket: 'shop-games-user-registros.appspot.com',
    iosBundleId: 'com.example.shopGamesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzflo4sWD4wIyU6hFKco14subtVlKOP-k',
    appId: '1:951446477589:web:bf46c62eada1b0b557e71c',
    messagingSenderId: '951446477589',
    projectId: 'shop-games-user-registros',
    authDomain: 'shop-games-user-registros.firebaseapp.com',
    storageBucket: 'shop-games-user-registros.appspot.com',
    measurementId: 'G-CSFKM4YCHB',
  );
}
